import { z } from './openapi.js';

/** Error code catalog (SRD CONV-004, plus SERVICE_UNAVAILABLE for /readyz, ADR 0005). */
export const ERROR_CODES = {
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  UNAUTHORIZED: 'UNAUTHORIZED',
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  FORBIDDEN: 'FORBIDDEN',
  ONBOARDING_REQUIRED: 'ONBOARDING_REQUIRED',
  EMAIL_NOT_VERIFIED: 'EMAIL_NOT_VERIFIED',
  RESOURCE_NOT_FOUND: 'RESOURCE_NOT_FOUND',
  CONFLICT: 'CONFLICT',
  EMAIL_ALREADY_REGISTERED: 'EMAIL_ALREADY_REGISTERED',
  CODING_PROFILE_ALREADY_LINKED: 'CODING_PROFILE_ALREADY_LINKED',
  PAYLOAD_TOO_LARGE: 'PAYLOAD_TOO_LARGE',
  UNSUPPORTED_FILE_TYPE: 'UNSUPPORTED_FILE_TYPE',
  INVALID_CODING_USERNAME: 'INVALID_CODING_USERNAME',
  LIMIT_EXCEEDED: 'LIMIT_EXCEEDED',
  RATE_LIMITED: 'RATE_LIMITED',
  QUOTA_EXCEEDED: 'QUOTA_EXCEEDED',
  CODING_PROVIDER_UNAVAILABLE: 'CODING_PROVIDER_UNAVAILABLE',
  CODING_PLATFORM_DISABLED: 'CODING_PLATFORM_DISABLED',
  NEWS_PROVIDER_UNAVAILABLE: 'NEWS_PROVIDER_UNAVAILABLE',
  AI_PROVIDER_UNAVAILABLE: 'AI_PROVIDER_UNAVAILABLE',
  SERVICE_UNAVAILABLE: 'SERVICE_UNAVAILABLE',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];

export const ERROR_HTTP_STATUS: Readonly<Record<ErrorCode, number>> = {
  VALIDATION_ERROR: 400,
  UNAUTHORIZED: 401,
  INVALID_CREDENTIALS: 401,
  FORBIDDEN: 403,
  ONBOARDING_REQUIRED: 403,
  EMAIL_NOT_VERIFIED: 403,
  RESOURCE_NOT_FOUND: 404,
  CONFLICT: 409,
  EMAIL_ALREADY_REGISTERED: 409,
  CODING_PROFILE_ALREADY_LINKED: 409,
  PAYLOAD_TOO_LARGE: 413,
  UNSUPPORTED_FILE_TYPE: 415,
  INVALID_CODING_USERNAME: 422,
  LIMIT_EXCEEDED: 422,
  RATE_LIMITED: 429,
  QUOTA_EXCEEDED: 429,
  CODING_PROVIDER_UNAVAILABLE: 503,
  CODING_PLATFORM_DISABLED: 503,
  NEWS_PROVIDER_UNAVAILABLE: 503,
  AI_PROVIDER_UNAVAILABLE: 503,
  SERVICE_UNAVAILABLE: 503,
  INTERNAL_ERROR: 500,
};

export const errorCodeSchema = z.enum(Object.values(ERROR_CODES) as [ErrorCode, ...ErrorCode[]]);
